DROP TYPE IF EXISTS status CASCADE;
DROP TABLE IF EXISTS Categories CASCADE;
DROP TABLE IF EXISTS Inventory CASCADE;
DROP TABLE IF EXISTS Orders CASCADE;
DROP TABLE IF EXISTS Vend CASCADE;
DROP TABLE IF EXISTS VendOrder CASCADE;
DROP TABLE IF EXISTS Users CASCADE;